Using Modules

Modules allow for code-reuse and portability. Python is a batteries included language, meaning that lots of excellent modules
are already included in the base language.

Due to its legacy as a web programming
language, most of the standard libraries deal with network protocols and other topics
important to web development. The standard library modules are documented on the
main Python site


In [1]:
import math 
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

Writing and Using Your Own Modules

We will create a separate Py file as our module and import it to our interactive session:

In [2]:
from OwnModuleExample import sqrt 
sqrt(3)

9

In [3]:
import OwnModuleExample
dir(OwnModuleExample)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'sqrt']

In [4]:
OwnModuleExample.sqrt(3)

9

On adding a few changes to the module file (from sqrt return x*x to sqrt return x/2 in our function, and adding a poly func that was not there at the start), the code does not reflect the changes made to the module, as shown below: 

In [5]:
OwnModuleExample.sqrt(3)

9

Why? You have to importlib.reload in order to get new changes in your file
into the interpreter.

A directory called __pycache__ will automatically appear in
the same directory as our module.

This directory will automatically be
refreshed every time you make changes to your module file. It is important to never
include the __pycache__ directory into your Git repository because when others
clone your repository, if the filesystem gets the timestamps wrong, it could be that
__pycache__ falls out of sync with the source code.

Using a Directory as a Module

Beyond sticking all your Python code into a single file, you can use a directory to
organize your code into separate files. The trick is to put a __init__.py file in
the top level of the directory you want to import from. The file can be empty. 

--------------------------------------------------------------------------

Dynamic Importing

In case you do not know the names of the modules that you need to import ahead
of time, the __import__ function can load modules from a specified list of module
names.

In [8]:
sys = __import__('sys')   #import module from string argument
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

Namespaces distinguish between importing and running a Python script

In [ ]:
if __name__ == '__main__':
    #these statements are not executed during import
    #do run statements here 

#There is also __file__ which is the filename of the imported file.    

In addition
to the __init__.py file, you can put a __main__.py file in the top level of
your module directory if you want to call your module using the -m switch on
the commandline. Doing this means the __init__.py function will also run

------------------------------------------------------------------------

1.0 NUMPY

Dtypes

In [1]:
import numpy as np 

a = np.array([0], np.int16) #16-bit integer
a.itemsize #returns in 8-bit bytes

2

In [2]:
a.nbytes

2

In [4]:
a = np.array([0], np.int64) #64-bit integer
a.itemsize 

8

In [5]:
#Numerical arrays will also follow the same pattern 
a = np.array([0,1,23,4], np.int64)
a.shape 

(4,)

In [6]:
a.nbytes 

32

In [7]:
#we cannot tack on extra elements to a Numpy array after creation 
#raises an index error 
a = np.array([1,2])
a[2] = 32

IndexError: index 2 is out of bounds for axis 0 with size 2

the block of memory has already been delineated and Numpy will
not allocate new memory and copy data without explicit instruction.

Also, once you
create the array with a specific dtype, assigning to that array will cast to that type:

In [8]:
x = np.array(range(5), dtype=int)
x[0] = 1.33 #float assignment does not match dtype
x

array([1, 1, 2, 3, 4])

In [10]:
x[0] = 'this is a string'

#Different to Matlab 

ValueError: invalid literal for int() with base 10: 'this is a string'

1.2 Multidimensional Arrays

In [11]:
# they follow the same pattern
a = np.array([[1,3],[4,5]]) #omitting dtype picks default 
a 

array([[1, 3],
       [4, 5]])

In [12]:
a.dtype 

dtype('int32')

In [13]:
a.shape

(2, 2)

In [14]:
a.flatten()

array([1, 3, 4, 5])

maximum limit on the number of dimensions depends on how it is configured
during the Numpy build (usually thirty-two). Numpy offers many ways to build
arrays automatically:

In [16]:
a = np.arange(10)  #same as range()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [18]:
a = np.linspace(0,1,5) #start stop step 
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

meshgrid is used to create coordinate grids from two or more 1D arrays, often for plotting or evaluating functions over a grid:

In [19]:
X, Y = np.meshgrid([1,2,3],[5,6]) 
X

array([[1, 2, 3],
       [1, 2, 3]])

In [20]:
Y

array([[5, 5, 5],
       [6, 6, 6]])

In [22]:
a = np.zeros([2,2])
a

array([[0., 0.],
       [0., 0.]])

In [23]:
#create Numpy arrays using functions, 
np.fromfunction(lambda i,j: abs(i-j)<=1, (4,4))

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False,  True,  True,  True],
       [False, False,  True,  True]])

In [24]:
#we can have field names on np arrays 
a = np.zeros((2,2), dtype = [('x','f4')])
a['x']

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [25]:
x = np.array([(1,2)], dtype=[('value','f4'),('amount','c8')])
x['value']

array([1.], dtype=float32)

In [26]:
x['amount']

array([2.+0.j], dtype=complex64)

In [27]:
x = np.array([(1,9),(2,10),(3,11),(4,14)], dtype = [('value','f4'), ('amount','c8')])
x['value']

array([1., 2., 3., 4.], dtype=float32)

'value' is the field name for the first element in each tuple, and 'f4' is its data type, meaning it's a 32-bit floating point (single precision).

'amount' is the field name for the second element, and 'c8' is its data type, meaning it's a string of 8 characters (although numbers are provided, they'll be stored as strings).

In [28]:
#Numpy arrays can also be accessed by their attributes using recarray

y = x.view(np.recarray)
y.amount #access as attribute

array([ 9.+0.j, 10.+0.j, 11.+0.j, 14.+0.j], dtype=complex64)

Reshaping and Stacking Numpy Arrays

In [29]:
#we can stack arrays horizontally and vertically
x = np.arange(5)
y = np.array([9,10,11,12,13])

In [30]:
np.hstack([x,y])  #stacking them horizontally

array([ 0,  1,  2,  3,  4,  9, 10, 11, 12, 13])

In [31]:
np.vstack([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 9, 10, 11, 12, 13]])

There is also a dstack method if you want to stack in the third depth dimension.
Numpy np.concatenate handles the general arbitrary-dimension case. In some
codes (e.g., scikit-learn), you may find the terse np.c_ and np.r_ used to
stack arrays column-wise and row-wise:

In [32]:
np.c_[x,x]  #stack column-wise 


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [33]:
np.r_[x,x]  #stack row-wise

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

1.4 Duplicating Numpy Arrays

Numpy has a repeat function for duplicating elements and a more generalized
version in tile that lays out a block matrix of the specified shape:

In [34]:
x = np.arange(4)
np.repeat(x,2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [35]:
np.tile(x,(2,1))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [37]:
np.tile(x,(2,2))  #repeat twice across rows and columns 

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [39]:
#you can also have non-numerics like strings as items in the array:
np.array(['a','b','cow','dive'])

array(['a', 'b', 'cow', 'dive'], dtype='<U4')

'U4' refers to string length of 4, which is the longest string in the array (dive)

In [41]:
#Reshaping numpy arrays 
a =np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

you can be lazy and replace one of the dimensions above by negative one (i.e.,
reshape(-1,5) ), and Numpy will figure out the conforming of the other dimension.

The array transpose method operation is the same as the .T attribute:

In [42]:
a.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [44]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

1.5 Slicing, Logical Array Operations

Numpy arrays follow the same zero-indexed slicing logic as Python lists and strings:

In [47]:
x = np.arange(50).reshape(5,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
#the colon means select all along the indicated dimension(rows):
x[:,0] #all rows in the first column 

array([ 0, 10, 20, 30, 40])

In [49]:
x[0,:]  #all columns on the first row 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x = np.arange(2*3*4).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
x[:,1,[2,1]]  #index each dimension 

#: represents all (0th slice) axes - 1st dimension
#1 selects second row of each axis (index 1) -2nd dimension 
# [2,1] selects the elements at index 2 and index 1 from the selected row for each slice 


array([[ 6,  5],
       [18, 17]])

Numpy’s where function can find array elements according to specific logical
criteria. Note that np.where returns a tuple of Numpy indices,

In [52]:
np.where(x % 2 ==0)

#Here, the output is a tuple of arrays, with the first array representing the indices where x is even 
# (i.e., at positions 0, 1, 2).

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2], dtype=int64))

In [53]:
x[np.where (x %2 ==0)]

#Here, you’re selecting the actual values from x at the indices where
#  the condition is True (even numbers in this case).

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [54]:
x[np.where(np.logical_and(x%2 ==0, x<9))] #must meet the two conditions combined 

array([0, 2, 4, 6, 8])

1.6 Numpy Arrays and Memory

Numpy uses pass-by-reference semantics so that slice operations are views into
the array without implicit copying, which is consistent with Python’s semantics. 

This is particularly helpful with large arrays that already strain available memory.
In Numpy terminology, slicing creates views (no copying) and advanced indexing
creates copies.

1. If the indexing object (i.e., the item between the brackets) is a non-tuple sequence
object, another Numpy array (of type integer or boolean), or a tuple with at least one sequence object or Numpy array, then indexing creates copies. 

In [57]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
x[:,[0,1,2,2]]  #notice duplicated last dimension  

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
y=x[:,[0,1,2,2]]

Because of advanced indexing, the variable y has its own memory because the
relevant parts of x were copied. 

To prove it, we assign a new element to x and
see that y is not updated:

In [60]:
x[0,0] = 999 #changed element in x
x

array([[999.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [61]:
y  #NOT CHANGED

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

However, if we start over and construct y by slicing (which makes it a view) as
shown below, then the change we made does affect y because a view is just a
window into the same memory:

In [63]:
x = np.ones((3,3))
y = x[:2,:2]  #view of uper left piece
x[0,0] = 999 #change value
x

array([[999.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [64]:
y

array([[999.,   1.],
       [  1.,   1.]])

Note that if you want to explicitly force a copy without any indexing tricks, you can
do y=x.copy().

 The code below works through another example of advanced
indexing versus slicing:

In [65]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [66]:
y = x[[0,1,2]]  #indexed by integer list to make copy 
y

array([0, 1, 2])

In [67]:
z = x[:3]
z

array([0, 1, 2])

In [68]:
x[0] = 999
x

array([999,   1,   2,   3,   4])

In [69]:
y  #y is not affected

array([0, 1, 2])

In [70]:
z #z is affected since it's a view (slicing happened)

array([999,   1,   2])

In the above example, y is a copy, not a view, because it was created using advanced
indexing, whereas z was created using slicing. Thus, even though y and z have the
same entries, only z is affected by changes to x. 

Overlapping Numpy arrays

Manipulating memory using views is particularly
powerful for signal and image processing algorithms that require overlapping
fragments of memory. 

Here is how to use advanced Numpy
to create overlapping blocks that do not actually consume additional memory:

In [1]:
import numpy as np
from numpy.lib.stride_tricks import as_strided 

x = np.arange(16).astype(np.int32)
y=as_strided(x,(7,4),(8,4))  #overlapped slices 
y

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15]])

The above code creates a range of integers and then overlaps the entries to create a
7x4 Numpy array. The final argument in the as_strided function are the strides,
which are the steps in bytes to move in the row and column dimensions, respectively.

Thus, the resulting array steps four bytes in the column dimension and eight bytes
in the row dimension. Because the integer elements in the Numpy array are four
bytes, this is equivalent to moving by one element in the column dimension and by
two elements in the row dimension.

The second row in the Numpy array starts at
eight bytes (two elements) from the first entry (i.e., 2) and then proceeds by four
bytes (by one element) in the column dimension (i.e., 2,3,4,5). 

The important part is that memory is re-used in the resulting 7x4 Numpy array. The code below
demonstrates this by reassigning elements in the original x array. The changes show
up in the y array because they point at the same allocated memory:

In [2]:
x[:2]  = 99  #assign every other value 
x

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
y #the changes appear because y is a view 

array([[99, 99,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15]])

Note that as_strided does not check that you stay within memory block
bounds. So, if the size of the target matrix is not filled by the available data, the
remaining elements will come from whatever bytes are at that memory location.

In other words, there is no default filling by zeros or other strategy that defends
memory block bounds.

One defense is to explicitly control the dimensions as shown below:

In [4]:

n = 8 #number of elements
x= np.arange(n)  #create array 
k = 5 #desired number of rows 
y = as_strided(x,(k,n-k+1),(x.itemsize,)*2)
y #view

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

1.7 Numpy Memory Data Structures 

In [5]:
#create an array of 16-bit integers and then explore it:

x = np.array([1], dtype=np.int16)

In [6]:
#to view the raw data:

bytes(x.data)

b'\x01\x00'

Notice the orientation of the bytes. Now, change the dtype to unsigned two-byte
big-endian integer:

In [8]:
x = np.array([1], dtype='>u2')
bytes(x.data)

b'\x00\x01'

Notice the orientation of the bytes. This is what little/big endian means
for data in memory. 

We can create Numpy arrays from bytes directly using
frombuffer, as shown below, Note the effect of using different dtypes:

In [9]:
np.frombuffer(b'\x00\x01', dtype=np.int8)

array([0, 1], dtype=int8)

In [10]:
np.frombuffer(b'\x00\x01', dtype=np.int16)

array([256], dtype=int16)

In [12]:
np.frombuffer(b'\x00\x01', dtype='>u2')

array([1], dtype='>u2')

Once a ndarray is created, you can re-cast it to a different dtype or change the
dtype of the view. Roughly speaking, casting copies data:

In [13]:
x = np.frombuffer(b'\x00\x01', dtype=np.int8)
x

array([0, 1], dtype=int8)

In [14]:
y = x.astype(np.int16)
y

array([0, 1], dtype=int16)

In [15]:
y.flags['OWNDATA']  #confirms that y is a copy 

True

Alternatively, we can re-interpret the data using a view:

In [16]:
y = x.view(np.int16)
y

array([256], dtype=int16)

In [18]:
y.flags['OWNDATA']

False

Note that y is not new memory, it is just referencing the existing memory and reinterpreting
it using a different dtype (hence False)

Numpy Memory Strides

A stride is the number of bytes to reach the
next consecutive array element. There is one stride per dimension. Consider the
following Numpy array:

In [19]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=np.int8)

bytes(x.data)

b'\x01\x02\x03\x04\x05\x06\x07\x08\t'

In [20]:
x.strides

(3, 1)

 The array x is a 2D array with shape (3, 3). The stride of 3 means you need to move 3 elements (3 bytes for int8 type) to move from one row to the next. 
 
 The stride of 1 means that to move to the next element within the same row, you need to move 1 byte (since each element is 1 byte)

If we wanted to index x[1,2], we have to use the following offset: 

In [21]:
offset = 3*1+1*2 
x.flat[offset]

6

The offset calculation 3* 1 + 1*2 is determining the flat (1D) index for accessing an element in the 2D array x using memory strides. 

3 is the row index we are targeting and 1 is the row stride.

1 corresponds to the column index we are targeting and 2 is the column index and the stride is still 1 (from (3,1)).

Full calculation: For the row index 3: Move 3 strides of size 1 = 3*1.  For the column index 2: Move 1 strides of size 2 = 1 * 2. 

This gives an offset of 5, meaning you're accessing the element at the flat index 5 in the flattened version of the array x. This corresponds to x.flat[5], which accesses the 6th element in a flattened view of x

----------------------------------------------------

Numpy supports C-order (i.e., row-major) and Fortran-order (i.e., column-major). Refer further to documentation on this,for understanding of the K,A,C,F Order, under __array__ method. But to show examples:

In [22]:
x = np.array([[1,2,3], [7,8,9]], dtype=np.int8, order='C')
x.strides

(3, 1)

In [23]:
x = np.array([[1,2,3], [7,8,9]], dtype =np.int8, order='F')
x.strides

(1, 2)

Note the difference between the strides for the two orderings. 

For C-order, it takes 3 bytes to move between the rows and 1 byte to move between columns, whereas for
Fortran-order, it takes 1 byte to move between rows, but 2 bytes to move between
columns. 

This pattern continues for higher dimensions:

In [24]:
x = np.arange(125).reshape((5,5,5)).astype(np.int8)  #creates a 3D array of shape (5,5,5)
x.strides

#each element is of type int8, which occupies one byte 

(25, 5, 1)

To understand the strides for the 3D array above, here is how memory is laid out in a row-major (C-style) format:

The last axis (axis=-1) is the "fastest changing" dimension. Moving along this axis means moving to the next element in the row.
The second-to-last axis (axis=-2) moves between rows.
The first axis (axis=0) moves between blocks of rows (planes).

In [26]:
x

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]], dtype=int8)

To move between planes (along axis=0), you need to move 25 bytes. (5rows*5 elements per row)

To move between rows (along axis=1), you need to move 5 bytes.(5 elements per row, to move to the next row, skip over 5 elements, thus 5*1 byte = 5 bytes)

To move between elements in a row (along axis=2), you need to move 1 byte.

In [25]:
x[1,2,3]

38

In [29]:
#to get the [1,2,3] element using byte offsets, we can do this:

offset = (25*1 + 5*2 +1*3)
x.flat[offset]

38

In [30]:
#creating views by slicing just changes the stride!

x = np.arange(3,dtype=np.int32)
x.strides 

(4,)

In [31]:
y = x[::-1] #slices the array in reverse order
y.strides

(-4,)

In [3]:
#Transposing also just swipes the stride:
import numpy as np
x=np.array([[1,2,3],[7,8,9]], dtype=np.int8, order='F')
x.strides

(1, 2)

In [4]:
y =x.T
y.strides  #negative 

(2, 1)

In general, reshaping does not just alter the stride but may sometimes make copies
of the data. The memory layout (i.e., strides) can affect performance because of
the CPU cache.

The CPU pulls in data from main memory in blocks so that if many items can consecutively be operated on in a single block then that reduces the number of transfers needed from main memory that speeds up computation

----------------------------------------------------

1.8 Array Element-Wise Operations

The usual pairwise arithmetic operations are element-wise in Numpy:

In [5]:
x*3 

array([[ 3,  6,  9],
       [21, 24, 27]], dtype=int8)

In [6]:
y = x/x.max() 
y 

array([[0.11111111, 0.22222222, 0.33333333],
       [0.77777778, 0.88888889, 1.        ]])

In [7]:
np.sin(y) * np.exp(-y)

array([[0.09922214, 0.17648072, 0.23444524],
       [0.32237812, 0.31917604, 0.30955988]])

It is easy to mess up in-place operations such as x -= x.T for Numpy arrays
so these should be avoided in general and can lead to hard-to-find bugs later

-------------------------------------------------------------------------------------

1.9 Universal Functions

Universal functions (ufuncs) are Numpy
functions that are optimized to compute Numpy arrays at the C-level (i.e., outside
the Python interpreter)

In [8]:
#compute the trigonometric sine:

a = np.linspace(0,1,20)
np.sin(a)

array([0.        , 0.05260728, 0.10506887, 0.15723948, 0.20897462,
       0.26013102, 0.310567  , 0.36014289, 0.40872137, 0.45616793,
       0.50235115, 0.54714315, 0.59041986, 0.63206143, 0.67195255,
       0.70998273, 0.74604665, 0.78004444, 0.81188195, 0.84147098])

In [9]:
#Python's equivalent would be from its math module:

from math import sin
[sin(i) for i in a]

[0.0,
 0.05260728333807213,
 0.10506887376594912,
 0.15723948186175024,
 0.20897462406278547,
 0.2601310228046501,
 0.3105670033203749,
 0.3601428860007191,
 0.40872137322898616,
 0.4561679296190457,
 0.5023511546035125,
 0.547143146340223,
 0.5904198559291864,
 0.6320614309590333,
 0.6719525474315213,
 0.7099827291448582,
 0.7460466536513234,
 0.7800444439418607,
 0.8118819450498316,
 0.8414709848078965]

The output is a list, not a Numpy array, and to process all the elements of a, we
had to use the list comprehensions to compute the sine. 

This is because Python’s math function only works one at a time with each member of the array. Numpy’s sine function does not need these extra semantics because the computing runs in the Numpy C-code outside of the Python interpreter.

---------------------------------------------------------------

1.10 Numpy Data Input/Output

In [8]:
#Numpy makes it easy to move data in and out of files:
import numpy as np 

#Numpy arrays can be saved to files:
x = np.arange(10) 
np.savetxt('sample.txt',x)

In [9]:
#Numpy arrays can also be loaded:

x = np.loadtxt('sample.txt')
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

--------------------------------------------------------------------------------

1.11 Linear Algebra 

The
main entryway to linear algebra functions in Numpy is via the linalg submodule,

In [10]:
np.linalg.eig(np.eye(3))  #returns the eigenvalues and eigenvectors of a 3x3 matrix 

EigResult(eigenvalues=array([1., 1., 1.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))

In [12]:
np.eye(3)*np.arange(3) #does not work as expected like the output above 

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

To get matrix row–column products, you can use the matrix object,

In [14]:
np.eye(3) * np.matrix(np.arange(3)).T  #transpose for row-column multiplication

matrix([[0.],
        [1.],
        [2.]])

More generally, you can use Numpy’s dot product,

In [15]:
a = np.eye(3) 
b = np.arange(3).T 

a.dot(b)

array([0., 1., 2.])

In [16]:
b.dot(b)

np.int64(5)

The advantage of dot is that it works in arbitrary dimensions. This is handy for
tensor-like contractions (see Numpy tensordot for more info).

there is also the @ notation for Numpy matrix multiplication: 

In [18]:
a = np.eye(3)
b = np.arange(3).T 

a @ b

array([0., 1., 2.])

-------------------------------------------------------------------------------

4.12 Broadcasting

Broadcasting is incredibly powerful, but it takes time to understand:

1. All input arrays with ndim smaller than the input array of largest ndim have 1’s
pre-pended to their shapes.
2. The size in each dimension of the output shape is the maximum of all the input
shapes in that dimension.
3. An input can be used in the calculation if it is the shape in a particular dimension
either matches the output shape or has value exactly 1.
4. If an input has a dimension size of 1 in its shape, the first data entry in that
dimension will be used for all calculations along that dimension. In other words,
the stepping machinery of the ufunc will simply not step along that dimension
when otherwise needed (the stride will be 0 for that dimension).

An easier way to think about these rules is the following:
1. If the array shapes have different lengths, then left-pad the smaller shape with
ones.

2. If any corresponding dimension does not match, make copies along the 1-
dimension.

3. If any corresponding dimension does not have a one in it, raise an error.

In [19]:
#consider this: 

x = np.arange(3)

y = np.arange(5)

...and you want to compute the element-wise product of these. The problem is that
this operation is not defined for arrays of different shapes. We can define what this
element-wise product means in this case with the following loop,

In [20]:
out = []

for i in x:
    for j in y:
        out.append(i*j)

out 

[np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(8)]

But now we have lost the input dimensions of x and y. We can conserve these by
reshaping the output as shown:

In [21]:
out = np.array(out).reshape(len(x), -1) #reshape to 3x5. -1 means infer the remaining dimension
out

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [22]:
#alternatively, think of it as a matrix outer product:

from numpy import matrix

out = matrix(x).T * y
out 

matrix([[0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4],
        [0, 2, 4, 6, 8]])

In [23]:
#But how can you generalize this to handle multiple dimensions?

#add a singleton dimension to y:

x[:, None].shape

(3, 1)

Now, if we try this
directly, broadcasting will handle the incompatible dimensions by making copies
along the singleton dimension:

In [24]:
x[:,None]*y 

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

works with more complicated expressions too :

In [25]:
from numpy import cos

x[:,None]*y + cos(x[:, None]+y)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.54030231,  0.58385316,  1.0100075 ,  2.34635638,  4.28366219],
       [-0.41614684,  1.0100075 ,  3.34635638,  6.28366219,  8.96017029]])

But what if you do not like the shape of the resulting array?...

In [26]:
x*y[:,None]  #change the placement of the singleton dimension 

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6],
       [0, 4, 8]])